### ISSUE TITLE
Curl Referer

### ISSUE THREAD

**Issue by caioluders** [googleinurl/SCANNER-INURLBR#1]
In the line 459 : 
`
curl_setopt($curl, CURLOPT_REFERER, "http://blog.inurl.com.br/" . md5(intval(rand() % 255) . intval(rand() % 255) . intval(rand() % 255) . intval(rand() % 255)));
`
Why did you set the referrer ? isn't an easy way to block the script ?

att
geolado | g3ol4d0

**Comment by eine** [comment]
Doesn't work , you must review again , because this really really not working !

**Comment by MrCl0wnLab** [comment]
## Fixed

- https://github.com/MrCl0wnLab/SCANNER-INURLBR (new repo)
  - https://github.com/MrCl0wnLab/SCANNER-INURLBR/commit/e8ce4285d32b0449135684028b5b571736a7551b
