### ISSUE TITLE
php issue

### ISSUE THREAD

**Issue by tbzhy** [googleinurl/SCANNER-INURLBR#11]
Hello

i use kali 2020 and when i run the comman this is the output i get

[ INFO ] INSTALLING THE LIBRARY php5-curl ex: php5-curl apt-get install

when i try to install library i get another error

12345@kali:~/SCANNER-INURLBR$ sudo apt-get install php5-curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php5-curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5-curl' has no installation candidate
123456456@kali:~/SCANNER-INURLBR$ 

please help

**Comment by Jmunsey859** [comment]
I'm currently having the same issue. Kali 2020.4
