### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: shuffle():

### ISSUE THREAD

**Issue by ahmedguetat62** [googleinurl/SCANNER-INURLBR#14]
PHP Fatal error:  Uncaught TypeError: shuffle(): Argument #1 ($array) must be of type array, bool given in E:\SCANNER-INURLBR\src\load\session.config.php:50
Stack trace:
#0 E:\SCANNER-INURLBR\src\load\session.config.php(50): shuffle(true)
#1 E:\SCANNER-INURLBR\inurlbr.php(122): require_once('E:\\SCANNER-INUR...')
#2 {main}
  thrown in E:\SCANNER-INURLBR\src\load\session.config.php on line 50

Fatal error: Uncaught TypeError: shuffle(): Argument #1 ($array) must be of type array, bool given in E:\SCANNER-INURLBR\src\load\session.config.php:50
Stack trace:
#0 E:\SCANNER-INURLBR\src\load\session.config.php(50): shuffle(true)
#1 E:\SCANNER-INURLBR\inurlbr.php(122): require_once('E:\\SCANNER-INUR...')
#2 {main}
  thrown in E:\SCANNER-INURLBR\src\load\session.config.php on line 50

**Comment by laurei11** [comment]
Outdated libraries?

**Comment by MrCl0wnLab** [comment]
## Fixed

- https://github.com/MrCl0wnLab/SCANNER-INURLBR (new repo)

- Fixed: https://github.com/MrCl0wnLab/SCANNER-INURLBR/commit/e8ce4285d32b0449135684028b5b571736a7551b
