### ISSUE TITLE
Not working for me :   --proxy 

### ISSUE THREAD

**Issue by Gaurav-Jadhav** [googleinurl/SCANNER-INURLBR#7]
i am able to get results without proxy but when i tried executing script with proxy it is not working.. Not getting any results.
--proxy localhost:8118
--proxy-http-file http_proxys.txt

tried this way..
./inurlbr.php --dork 'site:www.domain inurl:login' --proxy-file proxy_list.txt -s save.txt
./inurlbr.php --dork 'site:www.domain inurl:login' --proxy-http-file proxy_list.txt -s save.txt

**Comment by MrCl0wnLab** [comment]
## Fixed

- https://github.com/MrCl0wnLab/SCANNER-INURLBR (new repo)
