### ISSUE TITLE
dork scanning 

### ISSUE THREAD

**Issue by Sicks3c** [googleinurl/SCANNER-INURLBR#8]
Hello 
I want to make a dork scan in google and I want to save it into a file ( without scanning any vulnerabilities ) 
I put that code 
`./inurlbr --dork ' index of /wp-content/uploads' -q 1,2,3 --save-as wp.txt `
What happens if he search and find website with the dork but they are not saved in the wp.txt

**Comment by MrCl0wnLab** [comment]
## Fixed

- https://github.com/MrCl0wnLab/SCANNER-INURLBR (new repo)
